### ISSUE TITLE
What am I doing wrong?

### ISSUE THREAD

**Issue by mvrozanti** [keon/deep-q-learning#11]
[I'm trying to test this out using a minor TicTacToe game](https://gist.github.com/mvrozanti/2f6a38a148c7c18f694e194c556d7b52) but I'm failing miserably for days. DQN keeps choosing negative rewards.

**Comment by haoran-zhang** [comment]
You can see the new issue I posted, there is a bug in this implementation.
I also failed at my first try on Lunar-Lander game. 
Btw, the repo is already cold maybe ...

**Comment by keon** [comment]
I fixed it. sorry guys for taking too long
