### ISSUE TITLE
a hidden bug in your code

### ISSUE THREAD

**Issue by haoran-zhang** [keon/deep-q-learning#12]
`for e in range(EPISODES):

        state = env.reset()

        state = np.reshape(state, [1, state_size])

        for time in range(500):

            # env.render()

            action = agent.act(state)

            next_state, reward, done, _ = env.step(action)

            reward = reward if not done else -10

            next_state = np.reshape(next_state, [1, state_size])

            agent.remember(state, action, reward, next_state, done)

            state = next_state

            if done:

                print("episode: {}/{}, score: {}, e: {:.2}"

                      .format(e, EPISODES, time, agent.epsilon))

                break

        if len(agent.memory) > batch_size:

            agent.replay(batch_size)`

Hi, I find a bug in your code.

The agent.replay(batch_size) should be in the inner loop,  means train_on_batch each time step, not each episode.

Your version can pass the cart-pole, but not the lunar-lander (also from openai gym)

The formal algorithm is followed.

<img width="627" alt="algorithm" src="https://user-images.githubusercontent.com/20435480/37595811-15aedf3c-2bb5-11e8-83cd-b2116af11caa.png">

The image from _Human-level control through deep reinforcement learning_   FYI

Go jackets!

**Comment by GarrisonD** [comment]
@haoran-zhang could you please upload your implementation without this bug somewhere? for example to github gist?

**Comment by haoran-zhang** [comment]
@GarrisonD I'm sorry, my code is a course project, which should not be online. The bug is severe but very easy to fix, just need to move agent.replay() into inner loop, that is. 


```
    for e in range(EPISODES):

        state = env.reset()

        state = np.reshape(state, [1, state_size])

        for time in range(500):

            # env.render()

            action = agent.act(state)

            next_state, reward, done, _ = env.step(action)

            reward = reward if not done else -10

            next_state = np.reshape(next_state, [1, state_size])

            agent.remember(state, action, reward, next_state, done)

            state = next_state

            if done:

                print("episode: {}/{}, score: {}, e: {:.2}"

                      .format(e, EPISODES, time, agent.epsilon))

                break

            if len(agent.memory) > batch_size:

                agent.replay(batch_size)

**Comment by keon** [comment]
@haoran-zhang thanks!
Sorry for the late reply.
I have been buried under works. I'll fix it according to advice.
Hope your project goes well :)
