### ISSUE TITLE
Speeding the replay

### ISSUE THREAD

**Issue by marxav** [keon/deep-q-learning#18]
First, thank you for this wonderful code.

In the `replay` function, there is one `model.fit(state, target_f)` per sample in the minibach (i.e. if there are 32 samples, then there are 32 `fit` ).

I think all samples of the minibatch could be used in a single update with one single `train_on_batch(states, targets_f)`, which would speed up the processing time.

**Comment by pskrunner14** [comment]
@marxav you are right, training on the minibatch showed significant improvement in performance and also helped speed up the process although I used `model.fit(states, targets_f)` not sure about `train_on_batch(states, targets_f)`

**Comment by pskrunner14** [comment]
@marxav you're right. Training on batches could speed up the process and result in stable convergence as well.

**Comment by keon** [comment]
yup. will do that someday if it is possible without hurting readability.
I chose one by one update because it fits the purpose of the demonstration.
