### ISSUE TITLE
What is the purpose of "done"?

### ISSUE THREAD

**Issue by shamoons** [keon/deep-q-learning#21]

**Comment by WorksWellWithOthers** [comment]
It shows if the agent failed at the game or succeeded. 
It is used as a trigger to reset the game.
For example if the agent was trying to learn Stage 1 in Super Mario, you would want to reset the agent and game to the very beginning position after dying. You would want to reset the position after reaching the goal in the end as well.
Check out these terms, "terminate state", "episodic problems", and "continuous problems".
Hope this helps.

**Comment by shamoons** [comment]
Sounds good. Thanks!
