### ISSUE TITLE
add cnn to dqn

### ISSUE THREAD

**Issue by skyer9** [keon/deep-q-learning#4]
https://yanpanlau.github.io/2016/07/10/FlappyBird-Keras.html

i think you may interested in this url

**Comment by skyer9** [comment]
https://github.com/rlcode/reinforcement-learning/blob/master/Code%203.%20Atari%20Game/1.%20Breakout/Breakout_DQN.py

sorry. i found this url just now.

**Comment by skyer9** [comment]
if you don't wanna maintaion this repo, how about inform it to everyone like below
https://github.com/blockstack-packages/community-deprecated/blob/master/README.md

**Comment by keon** [comment]
@skyer9 Sorry for the late response, I just updated the code for the repo :)
I will focus on minimalizing the code on this repo. I also plan to add some more games if I have time (probably using CNN).
So I believe I can keep this project going as it has different objective as RLCode's repo, which focuses on longer but easier code.
