### ISSUE TITLE
Plot Image

### ISSUE THREAD

**Issue by davsuacar** [keon/deep-q-learning#9]
First of all, thank you very much for your work. It was really helpful for me to understand RL. I would like to ask you the way you got the image display of the game. I didn't find it in the code. Thank you very much!

**Comment by keon** [comment]
@davsuacar do you mean that you want to see the game play? 
You can uncomment this line https://github.com/keon/deep-q-learning/blob/master/dqn.py#L77

**Comment by davsuacar** [comment]
Thank you very much!!

2017-10-20 17:28 GMT+02:00 Keon <notifications@github.com>:
